### ISSUE TITLE
Cannot run tasks from Pavlovia using Microsoft Edge

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#39]
The following errors occur:

![edge](https://user-images.githubusercontent.com/22459095/54365712-471a6a00-4667-11e9-9172-952e1c595374.png)

**Comment by u01ai11** [comment]
This also happens to me. I don't get those errors though -- just hangs with 'loading the experiment' when it works fine on all other browsers

**Comment by peircej** [comment]
@u01ai11 I think it would be better to handle your issue on the forum (discourse.psychopy.org) where we can get more information (and provide a link to your study for us to debug)

@dvbridges, I think this is fixed now, right? Wasn't it just an issue with trying to run on Edge before we had the no-modules system? Lets close the issue if it's fixed

**Comment by dvbridges** [comment]
@peircej , still not working, but there are no errors raised, only the loading screen. I cannot see anything wrong other than the fact the the JS files are not in the sources folder on Edge (at least my current version of Edge on Win 10:

```
Microsoft Edge 44.17763.1.0
Microsoft EdgeHTML 18.17763
```

**Comment by peircej** [comment]
I think this one needs @apitiot input

**Comment by apitiot** [comment]
As of version 3.1.1, PsychoJs now support both the current version of Edge and the future version (which is based on Chromium).

The issue had to do with Edge simply not running scripts whenever it encountered an unsupported Javascript feature rather than actually raising an error...

I'm closing the issue.

**Comment by u01ai11** [comment]
I know this is closed, but I still have this problem on 3.1.5? 

I don't desperately need to resolve this, just keeping you aware. 

tbh Edge has lot's of problems on other toolboxes (e.g. Lab.js), and with the Chromium changes the whole thing is likely to be a cat and mouse game for a while.

**Comment by peircej** [comment]
Yes, actually I found this again today as well on a simple task (sorry Alain, I don't have a link handy). Somewhat glad to hear it isn't just us that's found Edge hard to support. (One of the issues is that when it fails it often doesn't give an error message so Alain's just debugging blind!)

**Comment by peircej** [comment]
Actually, cancel that - it is working for me after all with a simple simple study. I was trying from an older version of PsychoPy.
I think we'll need to debug from your experiment @u01ai11. Could you send us the url please?

**Comment by peircej** [comment]
I haven't been able to reproduce the issue using 3.1.5 so closing again. @u01ai11 if you have an experiment you can point to that's failing will look again there. thanks

**Comment by apitiot** [comment]
Hello @u01ai11 ,

Following up on Jon's comment, could you share your experiment path for me to have a look?
As you point out, the Edge team has just about stopped solving issues on the current version of the browser (esentially they have thrown in the towel) with all efforts going towards the Chromium based next version.

Alain

**Comment by u01ai11** [comment]
Sure: here is the task https://run.pavlovia.org/u01ai11/rt/html/
Here is the repo: https://gitlab.pavlovia.org/u01ai11/rt

It's pretty much as simple as you can get -- present a square that disappears when you press a button, then repeat.

**Comment by u01ai11** [comment]
The same problem happens when run locally, it hangs on 'initializing experiment'
