### ISSUE TITLE
Chrome: Task not opening in full screen mode

### ISSUE THREAD

**Issue by dvbridges** [psychopy/psychojs#57]
After you start a task, by clicking `OK` in the starting GUI, the screen does not switch to full screen with Chrome, but it does with Firefox. However, if Chrome is not already full size, the browser will switch to full screen mode after the start up GUI.

_URL of an example task_
https://pavlovia.org/run/dvbridges/coloredrects/html/

**Comment by apitiot** [comment]
Hello @dvbridges ,

I have corrected the problem, which had to do with the quasi impossibility to consistently detect whether a browser window is already in full screen mode. I have removed that test and all seems to be working now.
The fix is available from version 3.1.0 onwards.
I am closing the issue.

Alain

**Comment by dvbridges** [comment]
Thanks @apitiot , although this issue is still being reported, and does not work for me using the above link. Is there something that extra I need to add to the code?

**Comment by apitiot** [comment]
Please try with 3.2.0.

**Comment by apitiot** [comment]
It should work now!
