### ISSUE TITLE
undefined 't' variable in line 188 of Clock.js

### ISSUE THREAD

**Issue by mtimoma** [psychopy/psychojs#78]
This is part of the 'reset' function for CountdownTimer. t is never initialized

**Comment by apitiot** [comment]
You are absolutely correct, of course. Well spotted!
I have just fixed it, and proted the fix all way back to version 3.1.1.
Thank you very much for bringing this to my attention.
Cheers,

Alain

**Comment by mtimoma** [comment]
My code is still giving the error of an undefined "t" and in the code on master branch I still see the t variable. Am I looking at/using the wrong version? Thanks!

**Comment by apitiot** [comment]
Could I ask you to clear your browser cache and try again? The code has been fixed.
